### ISSUE TITLE
Fails to build in a clean environment.  libgmp  404 error

### ISSUE THREAD

**Issue by blankmac** [anonymousbitcoin/anon#26]
Fetching libgmp...
failed: Connection timed out.
https://z.cash/depends-sources/libgmp-aece03c7b6967f91f3efdac8c673f55adff53ab1.tar.gz:
2018-08-18 01:15:04 ERROR 404: Not Found.
https://codeload.github.com/z-classic/libgmp/tar.gz//aece03c7b6967f91f3efdac8c673f55adff53ab1:
2018-08-18 01:15:05 ERROR 404: Not Found.

I snatched the dependency from Zen's servers, but you really shouldn't be relying on sources you don't control.

**Comment by ukminer17** [comment]
same error, please fix

**Comment by darthcrypto87** [comment]
Have you tried only running "./anonutil/build.sh" instead of "./anonutil/build.sh -j$(nproc)"?
Worked for me and another person too.

**Comment by blankmac** [comment]
As I said, I obtained the dependency elsewhere, I think you're missing the point of why I opened the issue.

**Comment by gregmeszaros** [comment]
This erros is because of the double quotes in the alternative dependency url

git diff
diff --git a/depends/packages/libgmp.mk b/depends/packages/libgmp.mk
index b6eafaf..e40d3cf 100644
--- a/depends/packages/libgmp.mk
+++ b/depends/packages/libgmp.mk
@@ -1,5 +1,5 @@
 package=libgmp

-$(package)_download_path=https://github.com/z-classic/$(package)/archive/
+$(package)_download_path=https://github.com/z-classic/$(package)/archive

 $(package)_file_name=$(package)-$($(package)_git_commit).tar.gz
 $(package)_download_file=$($(package)_git_commit).tar.gz

(not the removed end slash(/) in the second line)

**Comment by blankmac** [comment]
After retesting under the same conditions, the dependency that was failing is now available again without modification.
