### ISSUE TITLE
Error when sending ANON from a BTC imported key address

### ISSUE THREAD

**Issue by fabioganga** [anonymousbitcoin/anon#71]
### Describe the issue
When sending ANON from a BTC imported key address (hence address starting with 3ZN...) it is impossible to send ANON to a different address and the wallet returns an error

#### If so, please list the steps to reproduce below:
1.  Import a BTC key that qualifies for the airdrop
2.  Try to send the claimed ANON out to a different address

### Expected behaviour
It should work as usual just like any other An address...

### Actual behaviour + errors
The wallet returns the error "From address is invalid, it is too long" 
See screenshot here: https://ibb.co/ew4RjU

### The version of ANON you were using:
latest anond and anon-cli (1.3.0) and latest 1.0.2 Jar file

### Machine specs:
n/a

**Comment by nlevo** [comment]
An attempt to fix it can be found on the following [branch](https://github.com/anonymousbitcoin/anon/commits/fix/importprivkey). It hasn't been merged to the master yet, due to being tested. Please see if this fixes your issue.

**Comment by Lci80** [comment]
Had the same issue yesterday.The address you are trying to send it from strart with 3.Tried the above proposed fix and iti did not work.Use the anon-cli and issue the following command

anon-cli listaccounts
you should se something like "" or "2"  
In my case it was "2" so next is used
anon-cli sendfrom 2 "to anon address you want to send" "amount"
anon-cli sendfrom 2 AnfYxhj................ 1905 <- this is an example how it should look like

This worked for me 
For some reason the move command did not work an only after a couple of hours i tried the sendfrom command because i presumed that if move did not work sendfrom wont work either.
Hope it helps.

**Comment by savantor2** [comment]
You can send ANON from any address by doing…

$ ./src/anon-cli z_sendmany "$(YOUR ADDRESS)" "[{\"amount\": 0.1, \"address\": \"$(FRIEND ADDRESS)\"}]"

**Comment by savantor2** [comment]
$ ./src/anon-cli z_getoperationresult

The above command will provide the transaction hash to check it on the blockchain explorer

**Comment by nlevo** [comment]
Closed, it was fixed in this [commit](https://github.com/anonymousbitcoin/anon/commit/e6893cfb7ad146f8e8fdb6945bd4f5f3b8a020b2).
